DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS setup;
DROP TABLE IF EXISTS trade;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE setup (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  num_trades INTEGER NOT NULL
);

CREATE TABLE trade (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  setup_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  entry_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  entry_val FLOAT NOT NULL,
  comments TEXT NOT NULL,
  FOREIGN KEY (setup_id) REFERENCES setup (id),
  FOREIGN KEY (user_id) REFERENCES user (id)
);